const products =[
    { id: 1, name:"Casual Shirt", price: 1200, category: "Men Shirt", image:"images/casual.jpg"},
    { id: 2, name:"Formal Shirt", price: 3700, category: "Men Shirt", image:"images/images (1).jpg"},
    { id: 3, name:"Denim Shirt", price: 850, category: "Men Shirt", image:"images/download (11).jpg"},
    { id: 4, name:"Checked Shirt", price: 1000, category: "Men Shirt", image:"images/download (12).jpg"},
    { id: 5, name:"Crew Neck", price: 500, category: "Men TShirt", image:"images/download (13).jpg"},
    { id: 6, name:"Graphic T-Shirt", price: 1000, category: "Men TShirt", image:"images/download (8).jpg"},
    { id: 7, name:"Slim Fit", price: 999, category: "Men TShirt", image:"images/download (14).jpg"},
    { id: 8, name:"Pocket Tee", price:  750, category: "Men TShirt", image:"images/download (15).jpg"},
    { id: 9, name:"Normal Fit", price: 1000, category: "Men Jeans", image:"images/download (16).jpg"},
    { id: 10, name:"Loose Fit", price: 1300, category: "Men Jeans", image:"images/download (17).jpg"},
    { id: 11, name:"Cargo Jeans", price: 1500, category: "Men Jeans", image:"images/download (19).jpg"},
    { id: 12, name:"Baggy Jeans", price: 2000, category: "Men Jeans", image:"images/download (18).jpg"},
    { id: 13, name:"Hoodies", price: 2000, category: "Men Jackets", image:"images/download (20).jpg"},
    { id: 14, name:"windbreakers", price: 4000, category: "Men Jackets", image:"images/download (21).jpg"},
    { id: 15, name:"Down Jackets", price: 5999, category: "Men Jackets", image:"images/download (22).jpg"},
    { id: 16, name:"Parkas Jackets", price: 7000, category: "Men Jackets", image:"images/download (23).jpg"},
    { id: 17, name:"Casual Dress", price: 3800, category: "Women Dress", image:"images/download (28).jpg"},
    { id: 18, name:"Floral Dress", price: 2300, category: "Women Dress", image:"images/download (24).jpg"},
    { id: 19, name:"Party Dress", price: 6000, category: "Women Dress", image:"images/download (25).jpg"},
    { id: 20, name:"Wedding Dress", price: 10000, category: "Women Dress", image:"images/download (29).jpg"},
    { id: 21, name:"Casual Tops", price: 500, category: "Women Tops", image:"images/download (30).jpg"},
    { id: 22, name:"Denim Tops", price: 1000, category: "Women Tops", image:"images/download (31).jpg"},
    { id: 23, name:"White Tops", price: 1500, category: "Women Tops", image:"images/download (32).jpg"},
    { id: 24, name:"Floral Tops", price: 2000, category: "Women Tops", image:"images/download (33).jpg"},
    { id: 25, name:"Normal Fit", price: 850, category: "Women Jeans", image:"images/download (35).jpg"},
    { id: 26, name:"Loose Fit", price: 1000, category: "Women Jeans", image:"images/download (34).jpg"},
    { id: 27, name:"Cargo Jeans", price: 2000, category: "Women Jeans", image:"images/download (36).jpg"},
    { id: 28, name:"Baggy Jeans", price: 2500, category: "Women Jeans", image:"images/download (37).jpg"},
    { id: 29, name:"Hoodies", price: 2000, category: "Women Jackets", image:"images/download (38).jpg"},
    { id: 30, name:"windbreakers", price: 4000, category: "Women Jackets", image:"images/download (39).jpg"},
    { id: 31, name:"Down Jackets", price: 5999, category: "Women Jackets", image:"images/download (40).jpg"},
    { id: 32, name:"Parkas Jackets", price: 7000, category: "Women Jackets", image:"images/download (41).jpg"},
    { id: 33, name:"Crew Neck", price: 500, category: "Boys", image:"images/download (45).jpg"},
    { id: 34, name:"Graphic T-Shirt", price: 1000, category: "Boys", image:"images/download (46).jpg"},
    { id: 35, name:"Slim Fit", price: 999, category: "Boys", image:"images/download (47).jpg"},
    { id: 36, name:"Pocket Tee", price:  750, category: "Boys", image:"images/download (48).jpg"},
    { id: 37, name:"Casual Shirt", price: 1200, category: "Boys", image:"images/download (49).jpg"},
    { id: 38, name:"Formal Shirt", price: 1500, category: "Boys", image:"images/download (50).jpg"},
    { id: 39, name:"Denim Shirt", price: 850, category: "Boys", image:"images/download (51).jpg"},
    { id: 40, name:"Checked Shirt", price: 1000, category: "Boys", image:"images/images (2).jpg"},
    { id: 41, name:"Normal Fit", price: 1000, category: "Boys", image:"images/images (3).jpg"},
    { id: 42, name:"Loose Fit", price: 1300, category: "Boys", image:"images/download (53).jpg"},
    { id: 43, name:"Cargo Jeans", price: 1500, category: "Boys", image:"images/download (54).jpg"},
    { id: 44, name:"Baggy Jeans", price: 2000, category: "Boys", image:"images/download (52).jpg"},
    { id: 45, name:"Casual Dress", price: 3800, category: "Girls", image:"images/download (55).jpg"},
    { id: 46, name:"Floral Dress", price: 2300, category: "Girls", image:"images/download (42).jpg"},
    { id: 47, name:"Party Dress", price: 6000, category: "Girls", image:"images/download (56).jpg"},
    { id: 48, name:"Kids Frock", price: 3000, category: "Girls", image:"images/download (43).jpg"},
    { id: 49, name:"Casual Tops", price: 500, category: "Girls", image:"images/download (57).jpg"},
    { id: 50, name:"Denim Tops", price: 1000, category: "Girls", image:"images/download (58).jpg"},
    { id: 51, name:"White Shirt", price: 1500, category: "Girls", image:"images/download (59).jpg"},
    { id: 52, name:"Floral Tops", price: 2000, category: "Girls", image:"images/download (60).jpg"},
    { id: 53, name:"Crochet", price: 500, category: "Babys", image:"images/download (61).jpg"},
    { id: 54, name:"Denims", price: 1000, category: "Babys", image:"images/download (62).jpg"},
    { id: 55, name:"Cotton", price: 999, category: "Babys", image:"images/download (63).jpg"},
    { id: 56, name:"Pocket Tee", price: 750, category: "Babys", image:"images/download (64).jpg"},
]

